# Site
title: Silo
subtitle: arte e latitude rural

# URL
url: http://silo.org.br
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4666

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  tumblr: ""
  pinterest: ""
  github: "https://github.com/associacaosilo"
  instagram: ""
  twitter: ""
  facebook: ""
  youtube: ""
  vimeo: ""
  soundcloud: ""
  envelope-o: "mailto:contato@silo.org.br"
twitter_user: ""

# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _pages/404.md
    - _pages/noticias.md
    - _pages/quem-somos.md
    - _pages/projects
    - _sass
    - css
    - js
    - CNAME
    - TODO.md
    - media/favicons
    - media/swipebox
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "cover"
        field:
          element: "text"
          label: "imagem de capa"
          placeholder: "media/images/cover.jpg"
      - name: "category"
        field:
          element: "multiselect"
          label: "categorias do post (usar categoria 'silo' para posts genéricos)"
          placeholder: "clique aqui"
          options:
            - name: 'Silo'
              value: 'silo'
            - name: 'Encontrada'
              value: 'encontrada'
            - name: 'Interactivos!'
              value: 'interactivos'
            - name: 'Residência'
              value: 'residencia'
      - name: "swipebox"
        field:
          element: "text"
          label: "prefixo dos arquivos de imagem para serem incluidos na galeria"
          placeholder: "p1_"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
          placeholder: "Colocar Aqui o Nome Da Página"
      - name: "permalink"
        field:
          element: "text"
          label: "link dessa página"
          placeholder: "/contato/"
    _pages/people:
      - name: "link"
        field:
          element: "text"
          label: "link pra página da pessoa"
          placeholder: "minhapagina.com.br"
      - name: "cover"
        field:
          element: "text"
          label: "imagem da pessoa"
          placeholder: "media/images/people/pessoa.jpg"
      - name: "category"
        field:
          element: "multiselect"
          label: ""
          placeholder: "clique aqui"
          options:
            - name: 'Diretoria'
              value: 'diretoria'
            - name: 'Associadas'
              value: 'associadas'
            - name: 'Conselho'
              value: 'conselho'
            - name: 'Equipe'
              value: 'equipe'
